### PR TITLE
Updating 3rd party dependencies and fixes

### PR DESCRIPTION
**Pull request by svanteschubert**
https://msv.java.net is finally down.
You are working on the most advanced sources of MSV but on a very low version number (ie. 2011.2-SNAPSHOT). The problem with the version number, there are Java artefacts able to be downloaded via Maven with version 2013.6.1, which lack many fixes and enhancement your branch did.
I double checked and there are no further fixes on their final artefact 2013.6.2-SNAPSHOT and took the opportunity to update all dependent 3rd party libraries including JDK 5 to 8 - as older JDK versions are hard to get these days and not necessarily secure - and switched to 2017.1-SNAPSHOT.

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Looks good to me. @kohsuke WDYT?

**Comment by svanteschubert** [comment]
Thanks Tatu (cowtowncoder) for the quick review.
We should try to move this update to Maven Central to avoid confusions with existing higher revision numbers available at Maven Central, which not providing your updates as provided by msv.java.net.
If we do not have access rights to Maven Central, we should ask for it at https://msv.java.net aka java_administrator_grp@oracle.com
And if the price is the update of copyright, I would not object from my point as actually Sun is now Oracle so nothing changes. I had been Sun employee as well and sent Kohsuke already mails 15 years ago.. ;)

I would be happy to make progress here, as our ODF Toolkit (incubating) is depending on MSV.

Thanks in advance! :)
Svante

**Comment by cowtowncoder** [comment]
Agreed, would be good to untangle versioning issue. I am in similar situation both wrt being ex-Sun-employee and relying on MSV (for Woodstox). :)

**Comment by cowtowncoder** [comment]
Made one minor change: required JDK baseline down to 6 (1.6). I think might even work with Java 5, but I need Java 6 baseline to be able to use new version with Woodstox 5.x (for Jackson 2.9, Java 7 baseline would be needed as well).

We can increase baseline in future if there are benefits, but I was thinking it makes sense to build first "new" version so that all/most deps can use it.

**Comment by svanteschubert** [comment]
Thanks for the merge, Tatu!

The JDK baseline downgrade is fine with me. We recently updated to JDK 8 at our Apache library. Due to missing security updates of former JDK (7 last public update was Apr 2015), it seemed correct to align customers to JDK 8 and to offer state-of-the-art toys to developers.
Nevertheless, I often hear the backwards compatibility argument, especially in context with LTS Linux distributions, but honestly, I don't care, sometimes you need to make a decision in favour of active developers.. ;)

Regarding Maven Central: What do you think? Would you take over as apparent active maintainer of MSV to try to get the access to Maven Central?
The common guide ...
https://maven.apache.org/guides/mini/guide-central-repository-upload.html
...references to the open source guide, which we might want to follow:
http://central.sonatype.org/pages/ossrh-guide.html
I suggest you might try to simply write them a ticket and put the Oracle admin on CC (if possible).

The last thing, is there something like a new home page necessary? Shall we spread clones in case this copy incidentally vanishes? Suggestions?
The https://nlnet.nl/ for instance offers https://commonsconservancy.org/ but one step after the other. :)

Enjoy your day,
Svante

**Comment by cowtowncoder** [comment]
Ok. So, I do not seem to have access at Maven Central: mvn release works up until final push. Oddly enough parent pom release seems to succeed, but not for any child components.
Could also be something wrong with project setup too, but I can push many other projects.

If kohsuke is around, he should have access.

**Comment by svanteschubert** [comment]
@kohsuke Could we make another version as mentioned above to integrate the patch I have provided?

I need it for https://issues.apache.org/jira/browse/ODFTOOLKIT-457

Thanks in advance :)
Svante

**Pull request merged**
